name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: |
          pip install poetry

     
      - name: Clear Poetry cache
        run: |
          poetry cache clear pypoetry --all || true

      - name: Install dependencies
        run: |
          poetry install

      - name: Lint with flake8
        run: |
          poetry run flake8 .

      - name: Type check with mypy
        run: |
          poetry run mypy .

      - name: Run tests
        run: |
          poetry run pytest -v
